name: Check macOS Updates

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y xmlstarlet jq

      - name: Run macOS Update Check
        run: ./get_latest_macOS_sofa.sh
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
